name = "Ventilador"
uuid = "5d98bd70-fb9d-4de9-8668-82594df3fe41"
authors = ["glrme-arauo <glrme_araujo@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
MQTTClient = "985f35cc-2c3d-4943-b8c1-f0931d5f0959"

[compat]
MQTTClient = "0.3.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
